---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-auth
  namespace: province
spec:
  encryptedData:
    .dockerconfigjson: AgBhNSdXqOWICVQTswUswL/EZFL5hTdf3hF439eufpUf8XOy1OcVTk5mfzkQWkdMMGebgHYQ9Pf7Bz8h2YTGKtbDk6RHz0K/m+cPrb4dxVX4lEXXyhDq8Galn2u6hj8sD51Trg9vOsgqj39ubt6ZDjs0nf9D7BcZiuvDkMAOPinkcSDWz3NlFrSWBpEa6jHL5NlTIieBg0pFbWFaed4yJCWGed08ZQGUde72r5aBun7QU1WxYkDjw9jg5K2XNn8qSuWv8RrZgQ+UzUmTeQtgoNaYClAGsI0V0Ak72JLulDJ4KLCLPkD917v2NWRdpvCUHT4XNxSu5lKz14pa48RDulnEgG0YRTn5XvIiEAnAOhwIL39dNdYlrJj1uyuRi2u0BQ2W2O7dmb3fvt/apih6pZ7K+Ilzz+ddjPd7CSXFH9+aRp8HcLIpQwAQBm3pKtO9y5pTpv/TkLx1TA5iHoE2upPlnd50uV29RDsHOenR3pBz2w1oJdkRiX1MkRAq7vvIum5PbTSyetRdd83Aj5Ue1H+jL2OOI5NESdP7bA1WbcHntT3bxMuhn6CmegUt3W8GbwRu+7+L2IOiEwQc3uS6Pzh6QJtnM6o6rKPpDjQD5b/mrW6BI1DpLN3CNzzCPXRqPihhU+CkxRetHa3jW4uWSwImil/Mf2dgHgaDzIzUHITLs58OTM1p7c6udcVuh4IZwKAraoW1ljUzHjRCPR+KeB2T9qggvrvARxfyqY8wUL+0xYza/7OlrxAUNvX6/9342eRzZT+/Qj+ilEpEiAo33/AnknIGP2R7byKt1AiaU1oXoKFXuJd/x2oODUUcX8vxyEBjUYbt4CLDQoSlf7PMoR08hHVQ8sJuM++I9xqMdErCLsIWxuZCSG4SdjeQSFZmAuWxchPWxdih/Edv1WFdlgdTBlgQ5Q==
  template:
    metadata:
      name: harbor-auth
      namespace: province
    type: kubernetes.io/dockerconfigjson
