---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: province-postgres
  namespace: province
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCJUHuVbPrfxVNmGREs5h5Ryb7K9gYR5+y0gvXIrsIPalXSfu9ZWTRlEhTxnSgeZKwrmyrcg2BMKKgLzIVm6qt2JMX4cwULQRpo2JUSoI5ovmoj5J+dZx6KktauTtC3D1nWZo2HBtRWNK5pGDCpQkKOmAvk+pIcSWqbHr/ao3Q7p7nPnYFtaAsobc8xHIGeHLu0ITjVfllvsY8yMeiyxBHkRCpIryaV/rURMbja0xvyn9/J3Wee+w4JZPODDCubOJMErs+DYoQ87rqFtQLaWddUHnAEWSI++CL8R7UGQ7ki7vjCIgIciNefR/JOI+NSzJKOcGxEUI6Q/Vux9YOcGaLHaDmTu6rkuIPQh31lYmusbHGQwTC9P9NvZbdJ0J7FrWV5xqG1vxDrmGE1oI7nAZT4ELk5BHDE6Q8U6IQHbqwLGed90R6Km3qH2JbqWeZZeqVXgxk3+R2ZgPY5IdoDc5O5SNq+PIcIianU0mAw4tD3o70Mrbk+vRpngvGT4YpeSVuMpG4dFOnq0LL96zq6v8wtUZL46bwyHIhSU1Onlur8S7gvC84a/Upchg/ZX2oCzUinC7PxkYM0Fdn2pj+eOFe27oLHyvPAShUlNDBcj/AqBdIo5TnbhvC7MDmVkpFXsxlH5NqRFUbRoUnASJAyApHZIy1Yy1weLK/WZhVoVpWOxYVf1WQK4Cc/MuiBGNcLGT5/duRaHwN8pH86BGpjEyKLO7tCi26y1VOWhmr1NHIj1D927jaskAjYvSSzeG5b364R2J/ePLmoQIGNlMlVYXl7
    POSTGRES_USER: AgCPtDVQbPZF5oGGGKQNY4IjnXeiNDHfWIukJqG1dFj926BLOr+/XaQT7FgYL7Co6qcLvjdMxzabijV4vfvvoc5mLGb7hldfYHZBknJND2CMF/Ef8R/9xwv5iFbUQT29MLJUdtUdLMDXvfbYwQxn6n+t+tUKXt+E7mnhFjtYO+/bh6VxPG580LLPBlD2LWt8iPzZyg/2CISDmBrKpqfcpU/2TfRrAyEuRzc+i+dnoiHSk1llWfTZz3KRKWxWPAxDO4dK8I7M4nVhHSu1xjieu9FORJjyA5AhEMlOLykA540TRqByYo7g4MO6Z9Usx75B5g87kRUbhaqbUsS3cI3Lkr5Rjsyr5QKA6pKStGWPHEr/rT48ECShyuwG4tS5LlZyrIbyx4PM8Ken//tdiaVYck4XwglPQUdexFFczUjkG9sNA7LrpTmjGehoVX3WIwtAzaIl+/9ElTLiGLexHHRVel6KNcaq68xuJIsK3v6xMDN2QMXdIIBcwgavVKCQgPtt5VnURdhTn5bl/hnxFbc4WX8IaMwHSZzDSla8mil4ALhvscaSIj+ESawySFHyUewpWy/ZCAN71Ty+7OzUTXf6nd6FEOdOALu0I4Tb3t0bjNz1deHldHXMi2RfxhRwy5n44gavUo229PYS0YeSzgJn51UIajsorZV5scZ8qf1KiBfcmPSaEJXkfFW8fEpOImlJNDJ+Qr8=
  template:
    metadata:
      name: province-postgres
      namespace: province
